"options":
  "debug":
    "default": !!bool "false"
    "type": "boolean"
    "description": "Enable debug logging"
  "verbose":
    "default": !!bool "false"
    "type": "boolean"
    "description": "Enable verbose logging"
  "use-syslog":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Setting this to True will allow supporting services to log to syslog.
  "use-internal-endpoints":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Openstack mostly defaults to using public endpoints for
      internal communication between services. If set to True this option
      will configure services to use internal endpoints where possible.
  "allowed_nets":
    "default": "p2p"
    "type": "string"
    "description": |
      String containing a list of allowed networks, separated by semicolons: e.g., "10.172.0.0/16;10.10.0.0/18"
  "forwarders":
    "default": ""
    "type": "string"
    "description": |
      String containing a list of forwarders, separated by semicolons: e.g., "8.8.8.8;10.1.1.1"
